_target_: gflownet.policy.conformers.egnn.EGNNPolicy

forward:
  n_gnn_layers: 7
  n_mlp_layers: 2
  egnn_hidden_dim: 128
  mlp_hidden_dim: 256
  separate_mlp_per_torsion: False
  use_fake_edges: False
  fake_edge_radius: 2.0
backward:
  n_gnn_layers: 7
  n_mlp_layers: 2
  egnn_hidden_dim: 128
  mlp_hidden_dim: 256
  separate_mlp_per_torsion: False
  use_fake_edges: False
  fake_edge_radius: 2.0
