defaults:
  - base

_target_: gflownet.envs.conformers.conformer.Conformer

# alanine dipeptide
smiles: 'CC(C(=O)NC)NC(=O)C'
torsion_angles: [[0, 1, 2, 3], [0, 1, 6, 7]]
path_to_dataset: './data/alanine_dipeptide_conformers_1.npy'
url_to_dataset: 'https://drive.google.com/uc?id=1r1KRGcpBhR3xaS8yt2i64dfMnJGgNj4C'

# ibuprofen
# smiles: 'CC(C)Cc1ccc(cc1)[C@@H](C)C(=O)O'
# torsion_angles: [[2, 1, 3, 4], [1, 3, 4, 5]]
# path_to_dataset: './data/ibuprofen_conformers_1.npy'
# url_to_dataset: 'https://drive.google.com/uc?id=1wRvaiQ0H2gP3gNqRfpwXRJJ4pF70ulyf'

id: conformer
policy_encoding_dim_per_angle: null
# Fixed length of trajectories
length_traj: 10
vonmises_min_concentration: 1e-3
# Parameters of the fixed policy output distribution
n_comp: 3
fixed_distribution:
  vonmises_mean: 0.0
  vonmises_concentration: 0.5
# Parameters of the random policy output distribution
random_distribution:
  vonmises_mean: 0.0
  vonmises_concentration: 0.001
# Buffer
buffer:
  data_path: null
  train: null
  test:
    type: grid
    n: 1000
    output_csv: conformer_test.csv
    output_pkl: conformer_test.pkl
